version: "3.9" 

services:
  backend:
    build:
      context: ./backend             # The directory to send to Docker
      dockerfile: files/Dockerfile   # The path to the Dockerfile, relative to the context
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/meteor

  frontend:
    build: ./frontend # Correct as the Dockerfile is at the root of ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: meteor
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"